"""Fix model loading

Revision ID: 10e8ec70dbca
Revises: 
Create Date: 2025-07-03 18:43:44.503314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10e8ec70dbca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_responses', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('response',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'closed'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('question',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('intent_inputs', schema=None) as batch_op:
        batch_op.alter_column('intent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('utterance',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_id_intent'))
        batch_op.drop_column('source')

    with op.batch_alter_table('intent_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
        batch_op.alter_column('intent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('response_text',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_id_intent'))

    with op.batch_alter_table('intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_intents_code'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('message_type',
               existing_type=mysql.ENUM('user', 'bot', 'staff'),
               type_=sa.String(length=50),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('user_type',
               existing_type=mysql.ENUM('customer', 'staff'),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('customer', 'staff'),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('user', 'bot', 'staff'),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_intents_code'), ['intent_code'], unique=True)

    with op.batch_alter_table('intent_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_id_intent'), ['intent_id'], unique=True)
        batch_op.alter_column('response_text',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('intent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('intent_inputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('idx_id_intent'), ['intent_id'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('utterance',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('intent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('answer',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('start_time', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('active', 'closed'),
               existing_nullable=True)

    with op.batch_alter_table('chatbot_responses', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('keyword',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
